### ISSUE TITLE
Tarea del Modulo 1.1

### ISSUE THREAD

**Issue by Xadaniperez** [SistemasTecTlaxiaco/CursoGitHubXadani#1]
¿Por qué querías usar GitHub en el aula de clases?

**Comment by Xadaniperez** [comment]
Los estudiantes pueden mostrar sus proyectos en GitHub como parte de su evidencia, lo que puede ser útil para oportunidades laborales o académicas.

**Comment by josealfredo79** [comment]
Muy bien hecha la tarea 1.1
