### ISSUE TITLE
Asignacion modulo 1.3

### ISSUE THREAD

**Issue by Xadaniperez** [SistemasTecTlaxiaco/CursoGitHubXadani#3]
![image](https://github.com/user-attachments/assets/48820920-a676-403e-9e44-2f2dac54a9a1)
![image](https://github.com/user-attachments/assets/e55c03b2-cf80-4635-9612-f8cd8c2bf30a)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...la tarea 1.3 del modulo 1
