### ISSUE TITLE
Tarea Módulo 2.1

### ISSUE THREAD

**Issue by Xadaniperez** [SistemasTecTlaxiaco/CursoGitHubXadani#5]
![image](https://github.com/user-attachments/assets/bf44505d-0277-433d-a7f8-b9adee795f07)
![image](https://github.com/user-attachments/assets/680b27eb-e804-41e3-ba78-d7c678fceae2)

**Comment by josealfredo79** [comment]
Bien hecho y revisada la tarea 2.1 del Modulo 2
